WITH SRC AS (
    SELECT * FROM {{ source('pos', 'country') }}
),
TRANSFORMED AS (
    SELECT
        FRANCHISE_ID,
        FIRST_NAME AS ONWER_FIRST_NAME,
        LAST_NAME AS OWNER_LAST_NAME,
        CITY AS OWNER_CITY,
        COUNTRY AS OWNER_COUNTRY,
        LOWER(E_MAIL) AS EMAIL,
        PHONE_NUMBER
    FROM SRC
    )

SELECT * FROM TRANSFORMED

create or replace TABLE TB_101.RAW_POS.COUNTRY (
	COUNTRY_ID NUMBER(18,0),
	COUNTRY VARCHAR(16777216),
	ISO_CURRENCY VARCHAR(3),
	ISO_COUNTRY VARCHAR(2),
	CITY_ID NUMBER(19,0),
	CITY VARCHAR(16777216),
	CITY_POPULATION VARCHAR(16777216)
);